apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "helm-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  limits:
  - default:
      memory: {{ .Values.limitDefaultMemory }}
      cpu: {{ .Values.limitDefaultCpu }}
    type: {{ .Values.limitType }}
