replicaCount: 2
namespace: webservers
image:
  repository: webserver
  pullPolicy: IfNotPresent
  tag: "v1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "webserver"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

ingress:
  enabled: true
  className: ""
  annotations: {}
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: 
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 100Mi
  
livenessProbePath: /ping
livenessProbePort: 3000
readinessProbeScheme: HTTP
readinessProbePath: /ping
readinessProbePort: 3000


restartPolicy: Always

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}


# for limitrange
limitDefaultMemory: 1024Mi
limitDefaultCpu: 1000m
limitType: Container

# for service
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
  